QuestionsAnswers/QuestionsAnswers/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

QuestionsAnswers/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.usuario.urls')),
    path('pregunta/', include('apps.pregunta.urls')),
    path('usuario/', include('apps.usuario.urls')),
]

apps/pregunta/urls.py
from django.urls import path

from apps.pregunta.views import list, delete, nuevo, edit, list_respuesta, nueva_respuesta, delete_respuesta, respuesta_correcta


urlpatterns = [
    path('', list, name='list'),
    path('nuevo', nuevo, name='nuevo'),
    path('editar/<id_pregunta>', edit, name='edit'),
    path('eliminar/<id_pregunta>/', delete, name='eliminar'),
    path('eliminar_respuesta/<id_respuesta>/', delete_respuesta, name='eliminar_respuesta'),
    path('respuesta_correcta/<id_respuesta>/', respuesta_correcta, name='respuesta_correcta'),
    path('list_respuesta/<id_pregunta>', list_respuesta, name='list_respuesta'),
    path('nueva_respuesta/<id_pregunta>', nueva_respuesta, name='nueva_respuesta'),
]

apps/pregunta/models.py
from django.db import models

from apps.usuario.models import Usuario

# Create your models here.
class Pregunta(models.Model):
    titulo = models.TextField(max_length=200)
    detalle_pregunta = models.TextField(max_length=200)
    fecha = models.DateTimeField()
    
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True)     

    def save(self, *args, **kwargs):
        self.titulo = (self.titulo).upper()
        return super(Pregunta, self).save(*args, **kwargs)
    
    #def __str__(self):
    #    return str(self.titulo)

    def get_respuestas(self):
        return self.respuesta_set.all()

class Respuesta(models.Model):
    detalle_respuesta = models.CharField(max_length=200)
    correcta = models.BooleanField(default=False)
    fecha = models.DateTimeField() 
    
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE) 

apps/pregunta/forms.py
from django import forms
from apps.pregunta.models import Pregunta, Respuesta

class PreguntaForm(forms.ModelForm):

    class Meta:

        model = Pregunta

        fields = { 
            'titulo',
            'detalle_pregunta',
        }

        labels = {
            'titulo': 'Titulo',
            'detalle_pregunta': 'detalle_pregunta',
        }

        widgets = {
            'titulo': forms.TextInput(attrs={'class':'form-control'}),
            'detalle_pregunta': forms.Textarea(attrs={'class':'form-control'}),
        }

class RespuestaForm(forms.ModelForm):

    class Meta:

        model = Respuesta

        fields = {
            'detalle_respuesta',
        }

        labels = {
            'detalle_respuesta': 'Detalle Respuesta',
        }

        widgets = {
            'detalle_respuesta': forms.Textarea(attrs={'class':'form-control'}),
        }

apps/pregunta/views.py
import json
from django.shortcuts import render
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import redirect
from django.db.models import Q
from django.utils import timezone

from apps.pregunta.models import Pregunta, Respuesta
from apps.usuario.models import Usuario
from apps.pregunta.forms import PreguntaForm, RespuestaForm
from apps.utils.ServiceResponse import ServiceResponse

# Create your views here.


def list(request):
    pregunta = Pregunta.objects.all().order_by('-fecha')
    query = request.GET.get("buscar")
    if query:
        pregunta = Pregunta.objects\
        .filter(titulo__icontains=query)

    paginator = Paginator(pregunta, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    contexto = {'page_obj': page_obj, 'page': page_number}
    return render(request, 'pregunta/list.html', contexto)

def delete(request, id_pregunta):
    mensaje = ''
    userId = request.user.id
    usuario = Usuario.objects.filter(user_id = userId).exists()
    pregunta = Pregunta.objects.get(id=id_pregunta)
    if usuario:
        usu = Usuario.objects.get(user_id = userId)
        if pregunta.usuario_id == usu.id:
            if request.method == 'POST':
                pregunta.delete()
                return redirect('list')
        else:
            mensaje='No es el creador de la pregunta'
    else:
        mensaje='Debe loguearse para poder eliminar una pregunta'
    return render(request, 'pregunta/delete.html', {'pregunta': pregunta, 'msg': mensaje})

def delete_respuesta(request, id_respuesta):
    mensaje = ''
    userId = request.user.id
    usuario = Usuario.objects.filter(user_id = userId).exists()
    respuesta = Respuesta.objects.get(id=id_respuesta)
    if usuario:
        usu = Usuario.objects.get(user_id = userId)
        if respuesta.pregunta.usuario_id == usu.id:
            if request.method == 'POST':
                respuesta.delete()
                return redirect('list')
        else:
            mensaje = 'No es el creador de la pregunta'
    return render(request, 'pregunta/delete_respuesta.html', {'respuesta': respuesta, 'msg': mensaje})


def respuesta_correcta(request, id_respuesta):
    userId = request.user.id
    respuesta = Respuesta.objects.get(id__exact=id_respuesta)
    id_pregunta = respuesta.pregunta_id
    usu = Usuario.objects.get(user_id = userId)
    if respuesta.pregunta.usuario_id == usu.id:
        cont = Respuesta.objects.filter(Q(pregunta_id=id_pregunta) & Q(correcta=True)).count()
        if cont == 0:
            respuesta.correcta = True
            respuesta.save()
            response = ServiceResponse()
            response.addData('ok')
            data = json.dumps(response.getResult())
            return HttpResponse(data, content_type='application/json')
    


def nuevo(request):
    mensaje = ''
    userId = request.user.id
    usuario = Usuario.objects.filter(user_id = userId).exists()
    if request.method == 'POST':
        form = PreguntaForm(request.POST, request.FILES)
        if form.is_valid():
            existe_pregunta = Pregunta.objects.filter(detalle_pregunta=request.POST['detalle_pregunta']).exists()
            if existe_pregunta:
                mensaje = 'Existe la pregunta'  
            else:
                pregunta = form.save(commit=False)
                pregunta.fecha = timezone.now()
                if usuario:
                    usu = Usuario.objects.get(user_id = userId)
                    pregunta.usuario_id = usu.id
                pregunta.save()
                return redirect('list')
    else:
        form = PreguntaForm()
    return render(request, 'pregunta/form.html', {'form': form, 'msg': mensaje})


def edit(request, id_pregunta):
    mensaje = ''
    pregunta = Pregunta.objects.get(id=id_pregunta)
    if request.method == 'GET':
        form = PreguntaForm(instance=pregunta)
    else :
        form = PreguntaForm(request.POST, instance=pregunta)
        if form.is_valid():
            count = Pregunta.objects.filter(Q(detalle_pregunta=request.POST['detalle_pregunta']) & ~Q(id = pregunta.id)).count()
            if count == 0: 
                form.save()
                return redirect('list')
            else:
                mensaje = 'Ya existe la pregunta'
    return render(request, 'pregunta/form.html', {'form':form, 'msg': mensaje })



def nueva_respuesta(request, id_pregunta):
    mensaje = ''
    if request.method == 'POST':
        form = RespuestaForm(request.POST, request.FILES)
        if form.is_valid():
            respuesta = form.save(commit=False)
            respuesta.pregunta_id = id_pregunta
            respuesta.fecha = timezone.now()
            respuesta.save()
            return redirect('/pregunta/list_respuesta/'+str(id_pregunta))
                        
    else:
        form = RespuestaForm()
    return render(request, 'pregunta/form_respuesta.html', {'form': form, 'msg': mensaje})


def list_respuesta(request, id_pregunta):
    respuesta = Respuesta.objects.filter(pregunta_id=id_pregunta).order_by('-correcta')
    query = request.GET.get("buscar")
    if query:
        respuesta = Respuesta.objects\
        .filter(Q(pregunta_id=id_pregunta) & Q(correcta__icontains=query))

    paginator = Paginator(respuesta, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    contexto = {'page_obj': page_obj, 'page': page_number}
    return render(request, 'pregunta/list_respuesta.html', contexto)

templates/pregunta/delete.html
{% extends 'base/_layout.html' %}

{% block content %}
<h1>Eliminar Pregunta</h1>
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-12 text-center">
          {% if msg %}
          <div class="bs-component">
            <div class="alert alert-dismissible alert-danger">
              <button class="close" type="button" data-dismiss="alert" _msthash="1922700" _msttexthash="19565">×</button>
              <font _mstmutation="1" _msthash="1325792" _msttexthash="2433548">
                <strong _mstmutation="1" _istranslated="1">¡Oh, Error!</strong>
                <i class="alert-link">No se puede eliminar</i> {{ msg }}
              </font>
            </div>
          </div>
          {% endif %}
        </div>
    </div>
    <h3>¿Desea Eliminar la pregunta: "{{pregunta.detalle_pregunta}} "?</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>  
    <a class="btn btn-default" href="{% url 'list' %}">Cancelar</a>
</form>

{% endblock %}

templates/pregunta/delete_respuesta.html
{% extends 'base/_layout.html' %}

{% block content %}
<h1>Eliminar Respuesta</h1>
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-12 text-center">
          {% if msg %}
          <div class="bs-component">
            <div class="alert alert-dismissible alert-danger">
              <button class="close" type="button" data-dismiss="alert" _msthash="1922700" _msttexthash="19565">×</button>
              <font _mstmutation="1" _msthash="1325792" _msttexthash="2433548">
                <strong _mstmutation="1" _istranslated="1">¡Oh, Error!</strong>
                <i class="alert-link">No se puede eliminar</i> {{ msg }}
              </font>
            </div>
          </div>
          {% endif %}
        </div>
    </div>
    <h3>¿Desea Eliminar la respuesta: "{{respuesta.detalle_respuesta}} "?</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>  
    <a class="btn btn-default" href="{% url 'list' %}">Cancelar</a>
</form>

{% endblock %}

templates/pregunta/form.html
{% extends 'base/_layout.html' %}
{% load static %}
{% block content %}

<div class="app-title">
  <div>
    <h1><i class="fa fa-dashboard"></i> Nueva Pregunta</h1>
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
    <li class="breadcrumb-item"><a href="/pregunta">Pregunta</a></li>
  </ul>
</div>
      
<div class="row">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">
        <form method="POST" action="{{ action }}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-sm-12 text-center">
              {% if msg %}
              <div class="bs-component">
                <div class="alert alert-dismissible alert-danger">
                  <button class="close" type="button" data-dismiss="alert" _msthash="1922700" _msttexthash="19565">×</button>
                  <font _mstmutation="1" _msthash="1325792" _msttexthash="2433548">
                    <strong _mstmutation="1" _istranslated="1">¡Oh, Error!</strong>
                    <i class="alert-link">No se puede guardar</i> {{ msg }}
                  </font>
                </div>
              </div>
              {% endif %}
            </div>
          </div>  
          
          <div class="row">
            <div class="col-lg-6 col-sm-4">
              <label for="">Título</label>
              {{form.titulo}}
              {% for error in form.titulo.errors %}
                <p class=text-danger>{{ error|escape }}</p>
              {% endfor %}
            </div>
            <div class="col-lg-6 col-sm-4">
              <label for="">Pregunta</label>
              {{form.detalle_pregunta}}
              {% for error in form.detalle_pregunta.errors %}
                <p class=text-danger>{{ error|escape }}</p>
              {% endfor %}
            </div>
          </div>
                    
          <div class="row">
            <div class="col-md-12 text-right">
              <br>
              <button class="btn btn-dark btn-sm" type="submit"><i class="fa fa-save"></i> Guardar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content%}

{% block extrajs %}

{% endblock %}

templates/pregunta/form_respuesta.html
{% extends 'base/_layout.html' %}
{% load static %}
{% block content %}

    <div class="app-title">
        <div>
          <h1><i class="fa fa-dashboard"></i> Registrar Respuesta</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item"><a href="/pregunta">Pregunta</a></li>-->
        </ul>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="tile">
            <div class="tile-body">
                <form method="POST" action="{{ action }}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-sm-12 text-center">
                          {% if msg %}
                            <div class="bs-component">
                              <div class="alert alert-dismissible alert-danger">
                                <button class="close" type="button" data-dismiss="alert" _msthash="1922700" _msttexthash="19565">×</button>
                                <font _mstmutation="1" _msthash="1325792" _msttexthash="2433548">
                                  <strong _mstmutation="1" _istranslated="1">¡Oh, Error!</strong>
                                  <i class="alert-link">No se puede guardar</i> {{ msg }}
                                </font>
                              </div>
                            </div>
                          {% endif %}
                      </div>
                    </div>  
                    <div class="row">
                        <div class="col-lg-4 col-sm-4">
                          <label for="">Detalle Respuesta</label>
                          {{form.detalle_respuesta}}
                          {% for error in form.detalle_respuesta.errors %}
                            <p class=text-danger>{{ error|escape }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    <div class="row">
                        <div class="col-md-12 text-right">
                            <br>
                            <button class="btn btn-dark btn-sm" type="submit"><i class="fa fa-save"></i> Guardar</button>
                        </div>
                    </div>

                </form>
            
            </div>
          </div>
        </div>
      </div>
    {% endblock content%}

  {% block extrajs %}

  {% endblock %}

templates/pregunta/list.html
{% extends 'base/_layout.html' %}
{% load static %}
{% block content %}

<div class="app-title">
    <div>
        <h1><i class="fa fa-dashboard"></i> Preguntas </h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>  
    </ul>
</div>
      
<div class="row">
    <div class="col-md-12">
        <div class="tile">         
            <div class="tile-body">
                <form method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Buscar por Título" name="buscar" value="{{ request.GET.buscar}}">
                        <div class="input-group-append" id="button-addon4">
                            <button class="btn btn-dark btn-sm" type="submit"><i class="fa fa-search"></i>Buscar</button>
                            <a class="btn btn-warning btn-sm" href="nuevo"><i class="fa fa-plus"></i> Nuevo </a>
                        </div>
                    </div>
                </form>
                    <table class="table table-striped table-sm table-responsive" id="lst_cat">
                        <thead>
                            <tr>
                                <th>Título</th>
                                <th>Pregunta</th>
                                <th>Fecha</th>
                                {% if user.groups.all.0.name == "Admin" %}
                                <th>Acciones</th>
                                {% endif %}
                                <th>Respuestas</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for p in page_obj %}
                            <tr>
                                <td>{{ p.titulo }}</td>
                                <td>{{ p.detalle_pregunta }}</td>
                                <td>{{ p.fecha }}</td>
                                {% if user.groups.all.0.name == "Admin" %}
                                <td>
                                    <a href="/pregunta/editar/{{ p.id }}"><i class="fa fa-pencil-alt"></i></a>
                                    <a href="/pregunta/eliminar/{{ p.id }}"><i class="fa fa-trash"></i></a>
                                </td>
                                {% endif %}
                                <td>
                                    <a href="/pregunta/list_respuesta/{{ p.id }}"><i class="fa fa-eye"></i></a>
                                    <a href="/pregunta/nueva_respuesta/{{ p.id }}"><i class="fa fa-plus"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        
                        </tbody>
                    </table>
                <!--{{ page }}-->
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item disabled">
                                <a href="?page={{ page_obj.previous_page_number }}" style="background-color:gold; border-color:gold; color: #000;">
                                    <span class="page-link" style="background-color:gold; border-color:gold; color: #000;"> Anterior</span>
                                </a>
                            </li>
                        {% endif %}

                        <li class="page-item active "><a class="page-link" href="#" style="background-color:gold; border-color:gold; color: #000;">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</a></li>
                        <!--{% for num in page_obj.paginator.page_range %}
                        <li class="page-item {% if page_obj.number == num %} active {% endif %}"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endfor %}-->

                         {% if page_obj.has_next %}
                             <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="background-color:gold; border-color:gold; color: #000;">
                                    <span>Siguiente</span>
                                </a>
                             </li>
                        {% endif %}

                    </ul>
                </nav>

            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block extrajs %}
{% endblock %}

templates/pregunta/list_respuesta.html
{% extends 'base/_layout.html' %}
{% load static %}
{% block content %}

<div class="app-title">
    <div>
        <h1><i class="fa fa-dashboard"></i> Respuestas </h1>
    </div>
    <ul class="app-breadcrumb breadcrumb">
        <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>  
        <li class="breadcrumb-item"><a href="/pregunta">Pregunta</a></li>
    </ul>
</div>
      
<div class="row">
    <div class="col-md-12">
        <div class="tile">         
            <div class="tile-body">
                <form method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="True o False" name="buscar" value="{{ request.GET.buscar}}">
                        <div class="input-group-append" id="button-addon4">
                            <button class="btn btn-dark btn-sm" type="submit"><i class="fa fa-search"></i>Buscar</button>
                        </div>
                    </div>
                </form>
                    <table class="table table-striped table-sm table-responsive" id="lst_cat">
                        <thead>
                            <tr>
                                <th>Respuesta</th>
                                <th>Correcta ó incorrecta</th>
                                <th>Fecha</th>
                                {% if user.groups.all.0.name == "Admin" %}
                                <th>Eliminar</th>
                                <th>Marcar Correcta</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for r in page_obj %}
                            <tr>
                                <td>{{ r.detalle_respuesta }}</td>
                                <td>{% if r.correcta %}Correcta{% else %}Incorrecta{% endif %}</td>
                                <td>{{ r.fecha }}</td>
                                {% if user.groups.all.0.name == "Admin" %}
                                <td>
                                    <a href="/pregunta/eliminar_respuesta/{{ r.id }}"><i class="fa fa-trash"></i></a>
                                </td>
                                <td>
                                    <a type="button" id="id_correcta" data-value="{{ r.id }}" href="#"><i class="fa fa-check"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        
                        </tbody>
                    </table>
                <!--{{ page }}-->
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item disabled">
                                <a href="?page={{ page_obj.previous_page_number }}" style="background-color:gold; border-color:gold; color: #000;">
                                    <span class="page-link" style="background-color:gold; border-color:gold; color: #000;"> Anterior</span>
                                </a>
                            </li>
                        {% endif %}

                        <li class="page-item active "><a class="page-link" href="#" style="background-color:gold; border-color:gold; color: #000;">Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</a></li>
                        <!--{% for num in page_obj.paginator.page_range %}
                        <li class="page-item {% if page_obj.number == num %} active {% endif %}"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                        {% endfor %}-->

                         {% if page_obj.has_next %}
                             <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="background-color:gold; border-color:gold; color: #000;">
                                    <span>Siguiente</span>
                                </a>
                             </li>
                        {% endif %}

                    </ul>
                </nav>

            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block extrajs %}
<script type="text/javascript" src="{% static 'js/respuesta/respuesta.js' %}"></script>
{% endblock %}